train:
  batch_size: 16
  learning_rate: 0.1
  decay_gamma: .5
  decay_step: 10
  epochs: 50

model:
  input_size: 40
  hidden_size: 256
  embedding_size: 256
  num_layers: 3

data:
  train_waveform_length: 152840 # in order to make spectrograms of length 150
  train_num_speakers: 246
  train_num_utterances: 80 # reasonable number to keep data standardized and not remove a lot of speakers
  validate_waveform_length: 102000 # validation waveforms are shorter, so lower length for less padding
  validate_num_speakers: 40
  validate_num_utterances: 36 # minimum number of utterances for speaker in validation data
  test_num_speakers: 5
  test_num_utterances: 5
  train_spec_length: 150
  validate_spec_length: 100
  spec_channels: 40

